---
abstract: 'Catalyst Collection Resources Controller'
author:
  - 'NAKAGAWA Masaki <masaki@cpan.org>'
build_requires:
  HTTP::Request: 0
  Test::More: 0
  Test::use::ok: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Controller-Resources
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Runtime: 5.7
  Class::C3: 0
  List::Util: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
