---
abstract: 'Catalyst Collection Resources Controller'
author:
  - 'NAKAGAWA Masaki <masaki@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  HTTP::Request: 0
  MRO::Compat: 0
  Test::More: 0
  Test::UseAllModules: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.88'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Controller-Resources
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Catalyst::Runtime: 5.80003
  Class::MOP: 0.84
  Filter::Util::Call: 0
  Moose: 0.79
  namespace::clean: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/masaki/catalyst-controller-resources.git
version: 0.07
